version: '3.8'

services:
  influxdb:
    image: influxdb:2.0
    volumes:
      - influxdb_data:/var/lib/influxdb2
    ports:
      - "8086:8086"
    env_file:
      - ./config/influxdb.env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8086/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

  data_collection:
    build: ./data
    volumes:
      - ./logs:/var/log/app 
      - ./device_info:/device_info
      - ./profiles:/profiles
      - ./data/app:/app # Mount the local directory for easier
    privileged: true
    restart: always

    # Uncomment the following lines to run the container in privileged mode (Used for profiling)
    # security_opt:
    #   - apparmor=unconfined  # Disable AppArmor restrictions
    # stop_grace_period: 30s
    # cap_add:
    #   - SYS_PTRACE  # Allow ptrace operations

    environment:
      - LOG_FILE=/var/log/app/data.log
      - INFLUXDB_URL=http://influxdb:8086
      - REDIS_URL=redis://redis:6379
    env_file:
      - ./config/influxdb.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      influxdb:
          condition: service_healthy
      redis:
          condition: service_healthy

  redis:
    image: redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  webapp:
    build: ./web
    privileged: true
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - influxdb
      - redis
      - data_collection
    volumes:
      - ./logs:/var/log/app 
      - ./web/app:/app
      - ./device_info:/device_info
      - ./app_data:/app_data
      - ./profiles:/profiles
    environment:
      - LOG_FILE=/var/log/app/web.log
      - INFLUXDB_URL=http://influxdb:8086
      - REDIS_URL=redis://redis:6379
    env_file:
      - ./config/auth.env
      - ./config/influxdb.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  influxdb_data:
  logs:
    driver: local
  profiles:
