version: '3.8'

services:
  influxdb:
    image: influxdb:2.0
    volumes:
      - influxdb_data:/var/lib/influxdb2
    ports:
      - "8086:8086"
    env_file:
      - ./config/influxdb.env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8086/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  data_collection:
    build: ./data
    volumes:
      - ./device_info:/app/device_info
    privileged: true
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - REDIS_HOST=redis
    env_file:
      - ./config/influxdb.env
    depends_on:
      influxdb:
        condition: service_healthy
      redis:
        condition: service_healthy
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  influxdb_data:
  device_info:

