version: '3.8'

services:
  influxdb:
    image: influxdb:2.0
    volumes:
      - influxdb_data:/var/lib/influxdb2
    ports:
      - "8086:8086"
    env_file:
      - ./config/influxdb.env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8086/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  data_collection:
    #Use Image not build
    build: ./data
    #image: data_collection:latest
    volumes:
      - ./device_info:/app/device_info
    privileged: true
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - REDIS_URL=redis://redis:6379
    env_file:
      - ./config/influxdb.env
    depends_on:
      influxdb:
          condition: service_healthy
      redis:
          condition: service_healthy

  redis:
    image: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  webapp:
    build: ./web
    privileged: true
    ports:
      - "8000:8000"
    depends_on:
      - influxdb
      - redis
      - data_collection
    volumes:
      - ./web/app:/app
      - ./device_info:/app/device_info
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - REDIS_URL=redis://redis:6379
    env_file:
      - ./config/auth.env

volumes:
  influxdb_data:
  device_info:
