version: '3.8'

services:
  influxdb:
    image: influxdb:2.0
    volumes:
      - influxdb_data:/var/lib/influxdb2
    ports:
      - "8086:8086"
    env_file:
      - ./config/influxdb.env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8086/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
  
  redis:
    image: redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
  
  nginx:
    image: nginx:1.27.2
    restart: always
    ports:
      - "8081:8081"  # Custom HTTP port
      - "443:443"  # Custom HTTPS port
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./etc/certs:/etc/nginx/certs  # Volume for SSL certificates
      - ./web/app/static:/app/static  # Mount the static files for Nginx
    depends_on:
      - webapp
      
  webapp:
    build: ./web
    privileged: true
    restart: always
    depends_on:
      - influxdb
      - redis
      - data_collection
    volumes:
      - ./etc/logs:/var/log/app # Log files
      - ./etc/profiles:/profiles # Profiling results 
      - ./etc/device_info:/device_info # Device information
      - ./etc/app_data:/app_data
      - ./etc/certs:/etc/nginx/certs  # Share certificates with NGINX

      - ./web/app:/app # Mount the local directory for easier development
      
    environment:
      - LOG_FILE=/var/log/app/web.log
      - INFLUXDB_URL=http://influxdb:8086
      - REDIS_URL=redis://redis:6379
    env_file:
      - ./config/auth.env
      - ./config/influxdb.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  data_collection:
    build: ./data
    volumes:
      - ./etc/logs:/var/log/app # Log files
      - ./etc/device_info:/device_info # Device information
      - ./etc/profiles:/profiles # Profiling results 
      - ./data/app:/app # Mount the local directory for easier
    privileged: true
    restart: always
    environment:
      - LOG_FILE=/var/log/app/data.log
      - INFLUXDB_URL=http://influxdb:8086
      - REDIS_URL=redis://redis:6379
    env_file:
      - ./config/influxdb.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      influxdb:
          condition: service_healthy
      redis:
          condition: service_healthy

volumes:
  influxdb_data:
